version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ~/Volumes/postgres/1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: myapp

  mariadb:
    image: mariadb
    volumes:
      - ~/Volumes/mariadb/1:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: myapp

  mongo:
    image: mongo
    volumes:
      - ~/Volumes/mongo/1:/db/data
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  elastic:
    image: elasticsearch:7.12.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ~/Volumes/elastic/1:/db/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "1000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on: 
      - postgres

  mongo-client:
    image: mongoclient/mongoclient
    ports:
      - "1002:3000"
    volumes:
      - "~/Volumes/mongoclient:/data/db mongoclient/mongoclient"
    depends_on:
      - mongo

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "1003:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb
