version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ~/Volume/postgres/1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: myapp

  mariadb:
    image: mariadb
    volumes:
      - ~/Volume/mariadb/1:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: myapp

  mongo:
    image: mongo
    volumes:
      - ~/Volume/mongo/1:/db/data
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: myapp

  redis:
    image: redis
    ports:
      - "6379:6379"